In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/rjmanoj/credit-card-customer-churn-prediction/Churn_Modelling.csv

In [2]:
df=pd.read_csv('/kaggle/input/datasets/rjmanoj/credit-card-customer-churn-prediction/Churn_Modelling.csv')

In [3]:
df.shape

(10000, 14)

In [4]:
df.sample(5)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
8417,8418,15689288,Folliero,630,France,Female,26,5,0.00,2,1,0,182612.38,0
2356,2357,15614934,McEwan,625,Germany,Female,37,4,142711.81,1,1,0,35625.41,0
5908,5909,15641934,Manna,749,Spain,Female,46,9,66582.81,1,1,0,78753.12,1
8259,8260,15703199,Golibe,619,Spain,Male,38,3,96143.47,1,0,0,98994.92,0
3609,3610,15657868,Serra,850,Germany,Male,40,6,94607.08,1,1,0,36690.49,0

In [5]:
df.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
df['Geography'].value_counts()

Geography
France     5014
Germany    2509
Spain      2477
Name: count, dtype: int64

In [9]:
df['Gender'].value_counts()

Gender
Male      5457
Female    4543
Name: count, dtype: int64

In [10]:
df['Exited'].value_counts()

Exited
0    7963
1    2037
Name: count, dtype: int64

In [11]:
df=df.drop(columns=['RowNumber','CustomerId','Surname'])
df.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [12]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [13]:
X=df.drop(columns=['Exited'])
y=df['Exited']

In [14]:
X.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,619,France,Female,42,2,0.00,1,1,1,101348.88
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58
2,502,France,Female,42,8,159660.80,3,1,0,113931.57
3,699,France,Female,39,1,0.00,2,0,0,93826.63
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10

In [15]:
y.head()

0    1
1    0
2    1
3    0
4    0
Name: Exited, dtype: int64

In [16]:
X

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,619,France,Female,42,2,0.00,1,1,1,101348.88
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58
2,502,France,Female,42,8,159660.80,3,1,0,113931.57
3,699,France,Female,39,1,0.00,2,0,0,93826.63
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10
...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77
9997,709,France,Female,36,7,0.00,1,0,1,42085.58
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78

In [17]:
import numpy as np
categorical_col=['Geography','Gender']

transformer=ColumnTransformer(transformers=[
    ('encode',OneHotEncoder(sparse_output=False,dtype=np.int32),categorical_col)
],remainder='passthrough')

In [18]:
X=transformer.fit_transform(X)

In [19]:
X = pd.DataFrame(
    X,
    columns=transformer.get_feature_names_out()
)

In [20]:
X.head()

,encode__Geography_France,encode__Geography_Germany,encode__Geography_Spain,encode__Gender_Female,encode__Gender_Male,remainder__CreditScore,remainder__Age,remainder__Tenure,remainder__Balance,remainder__NumOfProducts,remainder__HasCrCard,remainder__IsActiveMember,remainder__EstimatedSalary
0,1.0,0.0,0.0,1.0,0.0,619.0,42.0,2.0,0.00,1.0,1.0,1.0,101348.88
1,0.0,0.0,1.0,1.0,0.0,608.0,41.0,1.0,83807.86,1.0,0.0,1.0,112542.58
2,1.0,0.0,0.0,1.0,0.0,502.0,42.0,8.0,159660.80,3.0,1.0,0.0,113931.57
3,1.0,0.0,0.0,1.0,0.0,699.0,39.0,1.0,0.00,2.0,0.0,0.0,93826.63
4,0.0,0.0,1.0,1.0,0.0,850.0,43.0,2.0,125510.82,1.0,1.0,1.0,79084.10

In [21]:
X.columns = (
    X.columns
    .str.replace('encode__', '', regex=False)
    .str.replace('remainder__', '', regex=False)
)

In [22]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [23]:
X_train.head()

,Geography_France,Geography_Germany,Geography_Spain,Gender_Female,Gender_Male,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
9254,1.0,0.0,0.0,0.0,1.0,686.0,32.0,6.0,0.00,2.0,1.0,1.0,179093.26
1561,0.0,1.0,0.0,0.0,1.0,632.0,42.0,4.0,119624.60,2.0,1.0,1.0,195978.86
1670,0.0,0.0,1.0,0.0,1.0,559.0,24.0,3.0,114739.92,1.0,1.0,0.0,85891.02
6087,1.0,0.0,0.0,1.0,0.0,561.0,27.0,9.0,135637.00,1.0,1.0,0.0,153080.40
6669,1.0,0.0,0.0,0.0,1.0,517.0,56.0,9.0,142147.32,1.0,0.0,0.0,39488.04

In [24]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [25]:
import tensorflow
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [26]:
model=Sequential()

In [27]:
model.add(Dense(10,activation='sigmoid',input_dim=13))
model.add(Dense(5,activation='sigmoid'))
model.add(Dense(1,activation='sigmoid'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
2026-08-02 20:55:19.568484: E external/local_xla/xla/stream_executor/cuda/cuda_platform.cc:51] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)

In [28]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 10)             │           140 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 5)              │            55 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │             6 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 201 (804.00 B)

 Trainable params: 201 (804.00 B)

 Non-trainable params: 0 (0.00 B)

In [29]:
model.compile(loss='binary_crossentropy',optimizer='Adam',metrics=['accuracy'])

In [30]:
X_train.shape

(8000, 13)

In [31]:
model.fit(X_train,y_train,epochs=100,validation_split=0.2)

Epoch 1/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.6166 - loss: 0.6514 - val_accuracy: 0.7987 - val_loss: 0.5456
Epoch 2/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7934 - loss: 0.5160 - val_accuracy: 0.7987 - val_loss: 0.4885
Epoch 3/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7934 - loss: 0.4878 - val_accuracy: 0.7987 - val_loss: 0.4714
Epoch 4/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7934 - loss: 0.4737 - val_accuracy: 0.7987 - val_loss: 0.4576
Epoch 5/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7934 - loss: 0.4608 - val_accuracy: 0.7987 - val_loss: 0.4454
Epoch 6/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7934 - loss: 0.4500 - val_accuracy: 0.7987 - val_loss: 0.4362
Epoch 7/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7970 - loss: 0.4423 - val_accuracy: 0.8163 - val_loss: 0.4300
Epoch 8/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8080 - loss: 0.4372 - val_accuracy: 0.8219 - val_loss: 0.4261
Epoch 9/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8136 - loss: 0.4340 - val_accuracy: 0.8269 - val_loss: 0.4234
Epoch 10/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8128 - loss: 0.4316 - val_accuracy: 0.8244 - val_loss: 0.4213
Epoch 11/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8161 - loss: 0.4298 - val_accuracy: 0.8231 - val_loss: 0.4196
Epoch 12/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8183 - loss: 0.4281 - val_accuracy: 0.8256 - val_loss: 0.4179
Epoch 13/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8184 - loss: 0.4264 - val_accuracy: 0.8281 - val_loss: 0.4163
Epoch 14/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8208 - loss: 0.4247 - val_accuracy: 0.8281 - val_loss: 0.4149
Epoch 15/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8220 - loss: 0.4233 - val_accuracy: 0.8300 - val_loss: 0.4133
Epoch 16/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8256 - loss: 0.4215 - val_accuracy: 0.8306 - val_loss: 0.4122
Epoch 17/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8252 - loss: 0.4201 - val_accuracy: 0.8344 - val_loss: 0.4105
Epoch 18/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8263 - loss: 0.4188 - val_accuracy: 0.8344 - val_loss: 0.4093
Epoch 19/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8292 - loss: 0.4174 - val_accuracy: 0.8356 - val_loss: 0.4082
Epoch 20/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8308 - loss: 0.4163 - val_accuracy: 0.8350 - val_loss: 0.4071
Epoch 21/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8311 - loss: 0.4153 - val_accuracy: 0.8344 - val_loss: 0.4064
Epoch 22/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8317 - loss: 0.4142 - val_accuracy: 0.8356 - val_loss: 0.4054
Epoch 23/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8317 - loss: 0.4134 - val_accuracy: 0.8369 - val_loss: 0.4051
Epoch 24/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8319 - loss: 0.4125 - val_accuracy: 0.8363 - val_loss: 0.4041
Epoch 25/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8325 - loss: 0.4117 - val_accuracy: 0.8369 - val_loss: 0.4034
Epoch 26/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8327 - loss: 0.4110 - val_accuracy: 0.8381 - val_loss: 0.4028
Epoch 27/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8320 - loss: 0.4104 - val_accuracy: 0.8375 - val_loss: 0.4022
Epoch 28/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8341 - loss: 0.4098 - val_accuracy: 0.8363 - val_loss: 0.4018
Epoch 29/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8322 - loss: 0.4090 - val_accuracy: 0.8363 - val_loss: 0.4014
Epoch 30/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8341 - loss: 0.4083 - val_accuracy: 0.8375 - val_loss: 0.4009
Epoch 31/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8345 - loss: 0.4078 - val_accuracy: 0.8375 - val_loss: 0.4001
Epoch 32/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8350 - loss: 0.4068 - val_accuracy: 0.8344 - val_loss: 0.3995
Epoch 33/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8352 - loss: 0.4060 - val_accuracy: 0.8375 - val_loss: 0.3989
Epoch 34/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8359 - loss: 0.4053 - val_accuracy: 0.8350 - val_loss: 0.3981
Epoch 35/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8370 - loss: 0.4040 - val_accuracy: 0.8344 - val_loss: 0.3971
Epoch 36/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8366 - loss: 0.4030 - val_accuracy: 0.8350 - val_loss: 0.3959
Epoch 37/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8366 - loss: 0.4015 - val_accuracy: 0.8394 - val_loss: 0.3952
Epoch 38/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8381 - loss: 0.4004 - val_accuracy: 0.8375 - val_loss: 0.3939
Epoch 39/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8383 - loss: 0.3989 - val_accuracy: 0.8394 - val_loss: 0.3924
Epoch 40/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8388 - loss: 0.3974 - val_accuracy: 0.8394 - val_loss: 0.3909
Epoch 41/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8395 - loss: 0.3960 - val_accuracy: 0.8388 - val_loss: 0.3893
Epoch 42/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8394 - loss: 0.3943 - val_accuracy: 0.8381 - val_loss: 0.3879
Epoch 43/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8400 - loss: 0.3929 - val_accuracy: 0.8406 - val_loss: 0.3864
Epoch 44/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8383 - loss: 0.3908 - val_accuracy: 0.8400 - val_loss: 0.3854
Epoch 45/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8402 - loss: 0.3898 - val_accuracy: 0.8419 - val_loss: 0.3836
Epoch 46/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8413 - loss: 0.3883 - val_accuracy: 0.8425 - val_loss: 0.3819
Epoch 47/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8409 - loss: 0.3865 - val_accuracy: 0.8419 - val_loss: 0.3808
Epoch 48/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8420 - loss: 0.3850 - val_accuracy: 0.8413 - val_loss: 0.3791
Epoch 49/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8434 - loss: 0.3834 - val_accuracy: 0.8419 - val_loss: 0.3778
Epoch 50/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8434 - loss: 0.3820 - val_accuracy: 0.8431 - val_loss: 0.3764
Epoch 51/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8442 - loss: 0.3804 - val_accuracy: 0.8419 - val_loss: 0.3753
Epoch 52/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8445 - loss: 0.3790 - val_accuracy: 0.8456 - val_loss: 0.3741
Epoch 53/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8466 - loss: 0.3778 - val_accuracy: 0.8438 - val_loss: 0.3730
Epoch 54/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8470 - loss: 0.3763 - val_accuracy: 0.8450 - val_loss: 0.3715
Epoch 55/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8472 - loss: 0.3749 - val_accuracy: 0.8456 - val_loss: 0.3716
Epoch 56/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8478 - loss: 0.3738 - val_accuracy: 0.8475 - val_loss: 0.3699
Epoch 57/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8477 - loss: 0.3725 - val_accuracy: 0.8450 - val_loss: 0.3691
Epoch 58/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8483 - loss: 0.3713 - val_accuracy: 0.8462 - val_loss: 0.3680
Epoch 59/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8492 - loss: 0.3701 - val_accuracy: 0.8481 - val_loss: 0.3671
Epoch 60/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8494 - loss: 0.3689 - val_accuracy: 0.8512 - val_loss: 0.3663
Epoch 61/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8502 - loss: 0.3677 - val_accuracy: 0.8506 - val_loss: 0.3655
Epoch 62/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8486 - loss: 0.3668 - val_accuracy: 0.8519 - val_loss: 0.3648
Epoch 63/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8497 - loss: 0.3656 - val_accuracy: 0.8487 - val_loss: 0.3639
Epoch 64/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8508 - loss: 0.3642 - val_accuracy: 0.8512 - val_loss: 0.3630
Epoch 65/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8505 - loss: 0.3629 - val_accuracy: 0.8475 - val_loss: 0.3626
Epoch 66/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8509 - loss: 0.3622 - val_accuracy: 0.8444 - val_loss: 0.3622
Epoch 67/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8531 - loss: 0.3612 - val_accuracy: 0.8469 - val_loss: 0.3608
Epoch 68/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8534 - loss: 0.3603 - val_accuracy: 0.8500 - val_loss: 0.3597
Epoch 69/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8531 - loss: 0.3592 - val_accuracy: 0.8487 - val_loss: 0.3593
Epoch 70/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8534 - loss: 0.3581 - val_accuracy: 0.8519 - val_loss: 0.3588
Epoch 71/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8541 - loss: 0.3574 - val_accuracy: 0.8531 - val_loss: 0.3580
Epoch 72/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8548 - loss: 0.3560 - val_accuracy: 0.8525 - val_loss: 0.3569
Epoch 73/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8555 - loss: 0.3548 - val_accuracy: 0.8450 - val_loss: 0.3575
Epoch 74/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8555 - loss: 0.3545 - val_accuracy: 0.8525 - val_loss: 0.3555
Epoch 75/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8561 - loss: 0.3533 - val_accuracy: 0.8525 - val_loss: 0.3551
Epoch 76/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8559 - loss: 0.3526 - val_accuracy: 0.8519 - val_loss: 0.3545
Epoch 77/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8575 - loss: 0.3517 - val_accuracy: 0.8519 - val_loss: 0.3542
Epoch 78/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8569 - loss: 0.3509 - val_accuracy: 0.8506 - val_loss: 0.3536
Epoch 79/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8566 - loss: 0.3500 - val_accuracy: 0.8494 - val_loss: 0.3535
Epoch 80/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8564 - loss: 0.3495 - val_accuracy: 0.8525 - val_loss: 0.3523
Epoch 81/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8584 - loss: 0.3484 - val_accuracy: 0.8575 - val_loss: 0.3520
Epoch 82/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8589 - loss: 0.3478 - val_accuracy: 0.8531 - val_loss: 0.3519
Epoch 83/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8573 - loss: 0.3473 - val_accuracy: 0.8531 - val_loss: 0.3511
Epoch 84/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8595 - loss: 0.3468 - val_accuracy: 0.8506 - val_loss: 0.3507
Epoch 85/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8587 - loss: 0.3462 - val_accuracy: 0.8556 - val_loss: 0.3501
Epoch 86/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8577 - loss: 0.3454 - val_accuracy: 0.8569 - val_loss: 0.3503
Epoch 87/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8608 - loss: 0.3451 - val_accuracy: 0.8556 - val_loss: 0.3501
Epoch 88/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8602 - loss: 0.3443 - val_accuracy: 0.8562 - val_loss: 0.3492
Epoch 89/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8594 - loss: 0.3439 - val_accuracy: 0.8556 - val_loss: 0.3489
Epoch 90/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8597 - loss: 0.3435 - val_accuracy: 0.8581 - val_loss: 0.3485
Epoch 91/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8612 - loss: 0.3428 - val_accuracy: 0.8562 - val_loss: 0.3481
Epoch 92/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8606 - loss: 0.3424 - val_accuracy: 0.8569 - val_loss: 0.3481
Epoch 93/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8594 - loss: 0.3418 - val_accuracy: 0.8587 - val_loss: 0.3482
Epoch 94/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8611 - loss: 0.3412 - val_accuracy: 0.8562 - val_loss: 0.3484
Epoch 95/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8616 - loss: 0.3413 - val_accuracy: 0.8600 - val_loss: 0.3472
Epoch 96/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8606 - loss: 0.3408 - val_accuracy: 0.8587 - val_loss: 0.3467
Epoch 97/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8625 - loss: 0.3402 - val_accuracy: 0.8581 - val_loss: 0.3470
Epoch 98/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8606 - loss: 0.3399 - val_accuracy: 0.8581 - val_loss: 0.3466
Epoch 99/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8616 - loss: 0.3395 - val_accuracy: 0.8575 - val_loss: 0.3465
Epoch 100/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8609 - loss: 0.3392 - val_accuracy: 0.8569 - val_loss: 0.3464

In [32]:
model.layers[0].get_weights()

[array([[ 0.3892946 ,  0.5864417 ,  0.28482455,  0.00598654, -0.0447647 ,
         -0.08153479, -0.12121455,  0.48930484, -0.06350546, -0.00684849],
        [-1.0531076 , -0.14519879, -0.24391414, -0.7234811 ,  0.07599364,
          0.17644507,  0.3936967 , -0.11220328, -0.34651718,  0.01490638],
        [ 0.23275721, -0.17934251,  0.22046974, -0.45222646, -0.18363193,
         -0.49877286,  0.06053752,  0.15928552, -0.12417832,  0.41779768],
        [ 0.10318583, -0.22254562, -0.28997576, -0.47187096, -0.11296389,
         -0.24544157, -0.567154  , -0.2676405 , -0.31086814,  0.04018937],
        [ 0.06857288,  0.06878271,  0.15069552, -0.13591194,  0.01527912,
         -0.26096666,  0.00806879,  0.6469329 , -0.13784815,  0.11276335],
        [ 0.33594313,  0.42717183,  0.3058947 ,  0.05259788,  0.0770563 ,
          0.24204157,  0.34708098, -0.43535823, -0.1500304 , -0.24463084],
        [ 0.24039236, -1.4342471 , -0.16583247,  1.7664897 , -0.9217204 ,
         -1.7767276 ,  0.3681749 ,  0.47290483,  1.9947261 , -1.8304943 ],
        [ 0.14149936, -0.3870732 ,  0.06158079, -0.44297683, -0.01726681,
         -0.34562838, -0.01740933,  0.04838442, -0.25148916,  0.15029478],
        [-1.6950796 ,  0.7515994 , -0.43495494, -0.19320786, -0.7060044 ,
         -0.04991776, -0.31637424, -0.26192883, -0.5773156 , -0.5385251 ],
        [-1.5440719 , -0.7537019 ,  1.0001016 ,  0.7357873 , -3.9071553 ,
         -0.3470475 , -0.53897727, -0.47694877,  0.38484144, -0.90927446],
        [ 0.01291269, -0.36057714, -0.12430138, -0.2699799 , -0.12923002,
         -0.3727585 ,  0.11827051, -0.09315848,  0.06033432,  0.18252125],
        [-0.24384597, -0.8491983 , -1.2733395 ,  0.88864815, -0.53948325,
         -0.8671155 ,  1.4031184 ,  1.0865283 ,  0.9904535 , -0.9356652 ],
        [-0.01805171,  0.09561168, -0.12969273,  0.0432772 ,  0.01935072,
          0.28515413,  0.18927944, -0.34971377, -0.1975749 , -0.5918942 ]],
       dtype=float32),
 array([ 0.62991893, -1.0915715 , -0.00436991, -0.3631746 , -1.1053641 ,
         0.00282294, -0.55298454,  0.11933064, -0.2484421 ,  0.07164074],
       dtype=float32)]

In [33]:
y_pred=model.predict(X_test)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

In [34]:
from sklearn.metrics import accuracy_score
y_pred = model.predict(X_test)
y_pred = (y_pred > 0.5).astype(int)

from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
Accuracy: 0.863