In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/mohansacharya/graduate-admissions/Admission_Predict.csv
/kaggle/input/datasets/mohansacharya/graduate-admissions/Admission_Predict_Ver1.1.csv

In [10]:
df=pd.read_csv('/kaggle/input/datasets/mohansacharya/graduate-admissions/Admission_Predict.csv',index_col='Serial No.')

In [11]:
df.head()

,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
Serial No.,,,,,,,,
1,337,118,4,4.5,4.5,9.65,1,0.92
2,324,107,4,4.0,4.5,8.87,1,0.76
3,316,104,3,3.0,3.5,8.00,1,0.72
4,322,110,3,3.5,2.5,8.67,1,0.80
5,314,103,2,2.0,3.0,8.21,0,0.65

In [12]:
df.shape

(400, 8)

In [13]:
df.isnull().sum()

GRE Score            0
TOEFL Score          0
University Rating    0
SOP                  0
LOR                  0
CGPA                 0
Research             0
Chance of Admit      0
dtype: int64

In [14]:
df.duplicated().sum()

np.int64(0)

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 400 entries, 1 to 400
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   GRE Score          400 non-null    int64
 1   TOEFL Score        400 non-null    int64
 2   University Rating  400 non-null    int64
 3   SOP                400 non-null    float64
 4   LOR                400 non-null    float64
 5   CGPA               400 non-null    float64
 6   Research           400 non-null    int64
 7   Chance of Admit    400 non-null    float64
dtypes: float64(4), int64(4)
memory usage: 28.1 KB

In [20]:
print(df.columns)

Index(['GRE Score', 'TOEFL Score', 'University Rating', 'SOP', 'LOR ', 'CGPA',
       'Research', 'Chance of Admit '],
      dtype='object')

In [24]:
X=df.drop(columns=['Chance of Admit '])
y=df['Chance of Admit ']

In [25]:
X.head()

,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research
Serial No.,,,,,,,
1,337,118,4,4.5,4.5,9.65,1
2,324,107,4,4.0,4.5,8.87,1
3,316,104,3,3.0,3.5,8.00,1
4,322,110,3,3.5,2.5,8.67,1
5,314,103,2,2.0,3.0,8.21,0

In [35]:
X.shape

(400, 7)

In [26]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [30]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but MinMaxScaler was fitted without feature names
  warnings.warn(

In [32]:
X_train

array([[0.64      , 0.64285714, 0.5       , ..., 0.375     , 0.59935897,
        1.        ],
       [0.56      , 0.64285714, 0.5       , ..., 0.5       , 0.64102564,
        0.        ],
       [1.        , 1.        , 1.        , ..., 0.875     , 0.99679487,
        1.        ],
       ...,
       [0.32      , 0.46428571, 0.25      , ..., 0.5       , 0.45512821,
        1.        ],
       [0.24      , 0.25      , 0.        , ..., 0.25      , 0.14423077,
        0.        ],
       [0.48      , 0.5       , 0.25      , ..., 0.625     , 0.46474359,
        0.        ]])

In [33]:
import tensorflow
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [34]:
model=Sequential()

In [36]:
model.add(Dense(7,activation='relu',input_dim=7))
model.add(Dense(1,activation='linear'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
2026-08-04 21:32:39.076350: E external/local_xla/xla/stream_executor/cuda/cuda_platform.cc:51] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)

In [37]:
model.compile(loss='mse',optimizer='Adam',metrics=['mae'])

In [38]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 7)              │            56 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │             8 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 64 (256.00 B)

 Trainable params: 64 (256.00 B)

 Non-trainable params: 0 (0.00 B)

In [41]:
model.fit(X_train,y_train,epochs=200,validation_split=0.2)

Epoch 1/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0043 - mae: 0.0479 - val_loss: 0.0035 - val_mae: 0.0442
Epoch 2/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0044 - mae: 0.0482 - val_loss: 0.0036 - val_mae: 0.0443
Epoch 3/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0043 - mae: 0.0478 - val_loss: 0.0034 - val_mae: 0.0428
Epoch 4/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0043 - mae: 0.0474 - val_loss: 0.0034 - val_mae: 0.0429
Epoch 5/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0043 - mae: 0.0475 - val_loss: 0.0035 - val_mae: 0.0439
Epoch 6/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0043 - mae: 0.0477 - val_loss: 0.0034 - val_mae: 0.0433
Epoch 7/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0043 - mae: 0.0475 - val_loss: 0.0033 - val_mae: 0.0421
Epoch 8/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0043 - mae: 0.0480 - val_loss: 0.0035 - val_mae: 0.0437
Epoch 9/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0043 - mae: 0.0475 - val_loss: 0.0032 - val_mae: 0.0416
Epoch 10/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0043 - mae: 0.0471 - val_loss: 0.0034 - val_mae: 0.0427
Epoch 11/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0043 - mae: 0.0478 - val_loss: 0.0034 - val_mae: 0.0429
Epoch 12/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0043 - mae: 0.0473 - val_loss: 0.0032 - val_mae: 0.0411
Epoch 13/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0042 - mae: 0.0470 - val_loss: 0.0033 - val_mae: 0.0417
Epoch 14/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0042 - mae: 0.0472 - val_loss: 0.0033 - val_mae: 0.0419
Epoch 15/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0042 - mae: 0.0473 - val_loss: 0.0033 - val_mae: 0.0417
Epoch 16/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0042 - mae: 0.0467 - val_loss: 0.0031 - val_mae: 0.0407
Epoch 17/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0042 - mae: 0.0468 - val_loss: 0.0032 - val_mae: 0.0411
Epoch 18/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0042 - mae: 0.0469 - val_loss: 0.0032 - val_mae: 0.0415
Epoch 19/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0042 - mae: 0.0468 - val_loss: 0.0032 - val_mae: 0.0408
Epoch 20/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0042 - mae: 0.0465 - val_loss: 0.0032 - val_mae: 0.0410
Epoch 21/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0042 - mae: 0.0468 - val_loss: 0.0032 - val_mae: 0.0416
Epoch 22/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0042 - mae: 0.0466 - val_loss: 0.0031 - val_mae: 0.0404
Epoch 23/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0042 - mae: 0.0466 - val_loss: 0.0032 - val_mae: 0.0406
Epoch 24/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0042 - mae: 0.0466 - val_loss: 0.0032 - val_mae: 0.0407
Epoch 25/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0042 - mae: 0.0464 - val_loss: 0.0031 - val_mae: 0.0403
Epoch 26/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0042 - mae: 0.0463 - val_loss: 0.0032 - val_mae: 0.0407
Epoch 27/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0042 - mae: 0.0466 - val_loss: 0.0031 - val_mae: 0.0401
Epoch 28/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0042 - mae: 0.0464 - val_loss: 0.0031 - val_mae: 0.0404
Epoch 29/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0042 - mae: 0.0463 - val_loss: 0.0031 - val_mae: 0.0401
Epoch 30/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0042 - mae: 0.0463 - val_loss: 0.0031 - val_mae: 0.0396
Epoch 31/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0041 - mae: 0.0459 - val_loss: 0.0031 - val_mae: 0.0395
Epoch 32/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0041 - mae: 0.0463 - val_loss: 0.0031 - val_mae: 0.0404
Epoch 33/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0041 - mae: 0.0463 - val_loss: 0.0032 - val_mae: 0.0405
Epoch 34/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0041 - mae: 0.0459 - val_loss: 0.0030 - val_mae: 0.0392
Epoch 35/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0041 - mae: 0.0457 - val_loss: 0.0031 - val_mae: 0.0394
Epoch 36/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0041 - mae: 0.0466 - val_loss: 0.0033 - val_mae: 0.0420
Epoch 37/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0041 - mae: 0.0462 - val_loss: 0.0030 - val_mae: 0.0390
Epoch 38/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0041 - mae: 0.0457 - val_loss: 0.0031 - val_mae: 0.0398
Epoch 39/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0041 - mae: 0.0457 - val_loss: 0.0031 - val_mae: 0.0394
Epoch 40/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0041 - mae: 0.0463 - val_loss: 0.0032 - val_mae: 0.0407
Epoch 41/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0041 - mae: 0.0457 - val_loss: 0.0030 - val_mae: 0.0382
Epoch 42/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0041 - mae: 0.0458 - val_loss: 0.0032 - val_mae: 0.0408
Epoch 43/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0041 - mae: 0.0460 - val_loss: 0.0031 - val_mae: 0.0396
Epoch 44/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0041 - mae: 0.0454 - val_loss: 0.0030 - val_mae: 0.0387
Epoch 45/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0041 - mae: 0.0456 - val_loss: 0.0031 - val_mae: 0.0400
Epoch 46/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0041 - mae: 0.0457 - val_loss: 0.0031 - val_mae: 0.0397
Epoch 47/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0041 - mae: 0.0456 - val_loss: 0.0030 - val_mae: 0.0392
Epoch 48/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0041 - mae: 0.0454 - val_loss: 0.0030 - val_mae: 0.0384
Epoch 49/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0042 - mae: 0.0465 - val_loss: 0.0032 - val_mae: 0.0414
Epoch 50/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0041 - mae: 0.0452 - val_loss: 0.0029 - val_mae: 0.0380
Epoch 51/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0041 - mae: 0.0450 - val_loss: 0.0030 - val_mae: 0.0391
Epoch 52/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0041 - mae: 0.0460 - val_loss: 0.0031 - val_mae: 0.0406
Epoch 53/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0041 - mae: 0.0456 - val_loss: 0.0030 - val_mae: 0.0382
Epoch 54/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0041 - mae: 0.0450 - val_loss: 0.0030 - val_mae: 0.0385
Epoch 55/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0041 - mae: 0.0465 - val_loss: 0.0032 - val_mae: 0.0410
Epoch 56/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0041 - mae: 0.0454 - val_loss: 0.0030 - val_mae: 0.0382
Epoch 57/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0041 - mae: 0.0455 - val_loss: 0.0031 - val_mae: 0.0400
Epoch 58/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0040 - mae: 0.0454 - val_loss: 0.0030 - val_mae: 0.0387
Epoch 59/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0041 - mae: 0.0449 - val_loss: 0.0030 - val_mae: 0.0384
Epoch 60/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0040 - mae: 0.0452 - val_loss: 0.0031 - val_mae: 0.0401
Epoch 61/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0041 - mae: 0.0457 - val_loss: 0.0031 - val_mae: 0.0406
Epoch 62/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0041 - mae: 0.0453 - val_loss: 0.0029 - val_mae: 0.0378
Epoch 63/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0040 - mae: 0.0453 - val_loss: 0.0031 - val_mae: 0.0406
Epoch 64/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0041 - mae: 0.0454 - val_loss: 0.0030 - val_mae: 0.0388
Epoch 65/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0040 - mae: 0.0454 - val_loss: 0.0031 - val_mae: 0.0398
Epoch 66/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0041 - mae: 0.0460 - val_loss: 0.0031 - val_mae: 0.0400
Epoch 67/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0040 - mae: 0.0447 - val_loss: 0.0029 - val_mae: 0.0371
Epoch 68/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0040 - mae: 0.0447 - val_loss: 0.0030 - val_mae: 0.0396
Epoch 69/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0041 - mae: 0.0460 - val_loss: 0.0032 - val_mae: 0.0412
Epoch 70/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0040 - mae: 0.0453 - val_loss: 0.0029 - val_mae: 0.0376
Epoch 71/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0040 - mae: 0.0447 - val_loss: 0.0030 - val_mae: 0.0391
Epoch 72/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0040 - mae: 0.0454 - val_loss: 0.0030 - val_mae: 0.0397
Epoch 73/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0040 - mae: 0.0451 - val_loss: 0.0030 - val_mae: 0.0389
Epoch 74/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0040 - mae: 0.0449 - val_loss: 0.0030 - val_mae: 0.0390
Epoch 75/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0040 - mae: 0.0450 - val_loss: 0.0030 - val_mae: 0.0395
Epoch 76/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0040 - mae: 0.0451 - val_loss: 0.0030 - val_mae: 0.0384
Epoch 77/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0040 - mae: 0.0456 - val_loss: 0.0030 - val_mae: 0.0396
Epoch 78/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0040 - mae: 0.0446 - val_loss: 0.0029 - val_mae: 0.0375
Epoch 79/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0040 - mae: 0.0445 - val_loss: 0.0029 - val_mae: 0.0383
Epoch 80/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0040 - mae: 0.0460 - val_loss: 0.0032 - val_mae: 0.0412
Epoch 81/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0040 - mae: 0.0453 - val_loss: 0.0029 - val_mae: 0.0377
Epoch 82/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0040 - mae: 0.0445 - val_loss: 0.0030 - val_mae: 0.0386
Epoch 83/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0040 - mae: 0.0455 - val_loss: 0.0030 - val_mae: 0.0395
Epoch 84/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0040 - mae: 0.0447 - val_loss: 0.0029 - val_mae: 0.0375
Epoch 85/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0040 - mae: 0.0447 - val_loss: 0.0030 - val_mae: 0.0395
Epoch 86/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0040 - mae: 0.0450 - val_loss: 0.0030 - val_mae: 0.0386
Epoch 87/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0040 - mae: 0.0447 - val_loss: 0.0030 - val_mae: 0.0391
Epoch 88/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0040 - mae: 0.0453 - val_loss: 0.0030 - val_mae: 0.0393
Epoch 89/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0040 - mae: 0.0445 - val_loss: 0.0029 - val_mae: 0.0369
Epoch 90/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0040 - mae: 0.0443 - val_loss: 0.0030 - val_mae: 0.0391
Epoch 91/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0040 - mae: 0.0455 - val_loss: 0.0031 - val_mae: 0.0405
Epoch 92/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0040 - mae: 0.0449 - val_loss: 0.0029 - val_mae: 0.0379
Epoch 93/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0040 - mae: 0.0443 - val_loss: 0.0029 - val_mae: 0.0381
Epoch 94/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0040 - mae: 0.0448 - val_loss: 0.0031 - val_mae: 0.0399
Epoch 95/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0040 - mae: 0.0451 - val_loss: 0.0030 - val_mae: 0.0385
Epoch 96/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0040 - mae: 0.0444 - val_loss: 0.0029 - val_mae: 0.0374
Epoch 97/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0040 - mae: 0.0447 - val_loss: 0.0031 - val_mae: 0.0404
Epoch 98/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0040 - mae: 0.0451 - val_loss: 0.0030 - val_mae: 0.0386
Epoch 99/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0040 - mae: 0.0445 - val_loss: 0.0029 - val_mae: 0.0373
Epoch 100/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0040 - mae: 0.0445 - val_loss: 0.0031 - val_mae: 0.0399
Epoch 101/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0040 - mae: 0.0451 - val_loss: 0.0029 - val_mae: 0.0383
Epoch 102/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0040 - mae: 0.0448 - val_loss: 0.0030 - val_mae: 0.0384
Epoch 103/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0040 - mae: 0.0443 - val_loss: 0.0029 - val_mae: 0.0382
Epoch 104/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0040 - mae: 0.0449 - val_loss: 0.0030 - val_mae: 0.0398
Epoch 105/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0040 - mae: 0.0449 - val_loss: 0.0030 - val_mae: 0.0385
Epoch 106/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0040 - mae: 0.0443 - val_loss: 0.0029 - val_mae: 0.0370
Epoch 107/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0040 - mae: 0.0449 - val_loss: 0.0031 - val_mae: 0.0400
Epoch 108/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0040 - mae: 0.0455 - val_loss: 0.0029 - val_mae: 0.0380
Epoch 109/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0040 - mae: 0.0441 - val_loss: 0.0029 - val_mae: 0.0368
Epoch 110/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0040 - mae: 0.0453 - val_loss: 0.0032 - val_mae: 0.0420
Epoch 111/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0040 - mae: 0.0453 - val_loss: 0.0029 - val_mae: 0.0382
Epoch 112/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0040 - mae: 0.0442 - val_loss: 0.0029 - val_mae: 0.0372
Epoch 113/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0040 - mae: 0.0447 - val_loss: 0.0031 - val_mae: 0.0398
Epoch 114/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0040 - mae: 0.0452 - val_loss: 0.0030 - val_mae: 0.0393
Epoch 115/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0040 - mae: 0.0442 - val_loss: 0.0029 - val_mae: 0.0367
Epoch 116/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0040 - mae: 0.0452 - val_loss: 0.0030 - val_mae: 0.0396
Epoch 117/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0040 - mae: 0.0444 - val_loss: 0.0029 - val_mae: 0.0376
Epoch 118/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0040 - mae: 0.0448 - val_loss: 0.0030 - val_mae: 0.0389
Epoch 119/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0039 - mae: 0.0446 - val_loss: 0.0029 - val_mae: 0.0380
Epoch 120/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0040 - mae: 0.0444 - val_loss: 0.0029 - val_mae: 0.0377
Epoch 121/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0040 - mae: 0.0443 - val_loss: 0.0030 - val_mae: 0.0386
Epoch 122/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0040 - mae: 0.0448 - val_loss: 0.0030 - val_mae: 0.0390
Epoch 123/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0040 - mae: 0.0442 - val_loss: 0.0029 - val_mae: 0.0372
Epoch 124/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0039 - mae: 0.0443 - val_loss: 0.0031 - val_mae: 0.0403
Epoch 125/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0040 - mae: 0.0452 - val_loss: 0.0030 - val_mae: 0.0388
Epoch 126/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0039 - mae: 0.0442 - val_loss: 0.0029 - val_mae: 0.0374
Epoch 127/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0040 - mae: 0.0451 - val_loss: 0.0031 - val_mae: 0.0398
Epoch 128/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0039 - mae: 0.0441 - val_loss: 0.0029 - val_mae: 0.0373
Epoch 129/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0039 - mae: 0.0440 - val_loss: 0.0030 - val_mae: 0.0385
Epoch 130/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0039 - mae: 0.0446 - val_loss: 0.0030 - val_mae: 0.0396
Epoch 131/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0039 - mae: 0.0446 - val_loss: 0.0029 - val_mae: 0.0379
Epoch 132/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0040 - mae: 0.0441 - val_loss: 0.0029 - val_mae: 0.0381
Epoch 133/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0040 - mae: 0.0452 - val_loss: 0.0031 - val_mae: 0.0400
Epoch 134/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0040 - mae: 0.0444 - val_loss: 0.0029 - val_mae: 0.0378
Epoch 135/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0040 - mae: 0.0448 - val_loss: 0.0031 - val_mae: 0.0398
Epoch 136/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0039 - mae: 0.0444 - val_loss: 0.0029 - val_mae: 0.0376
Epoch 137/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0040 - mae: 0.0439 - val_loss: 0.0030 - val_mae: 0.0384
Epoch 138/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0040 - mae: 0.0448 - val_loss: 0.0031 - val_mae: 0.0399
Epoch 139/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0040 - mae: 0.0440 - val_loss: 0.0029 - val_mae: 0.0378
Epoch 140/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0039 - mae: 0.0442 - val_loss: 0.0030 - val_mae: 0.0391
Epoch 141/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0040 - mae: 0.0445 - val_loss: 0.0029 - val_mae: 0.0376
Epoch 142/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0039 - mae: 0.0443 - val_loss: 0.0030 - val_mae: 0.0395
Epoch 143/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0039 - mae: 0.0446 - val_loss: 0.0030 - val_mae: 0.0385
Epoch 144/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0039 - mae: 0.0441 - val_loss: 0.0030 - val_mae: 0.0384
Epoch 145/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0039 - mae: 0.0442 - val_loss: 0.0030 - val_mae: 0.0389
Epoch 146/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0039 - mae: 0.0440 - val_loss: 0.0029 - val_mae: 0.0382
Epoch 147/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0039 - mae: 0.0444 - val_loss: 0.0030 - val_mae: 0.0391
Epoch 148/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0039 - mae: 0.0442 - val_loss: 0.0030 - val_mae: 0.0386
Epoch 149/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0040 - mae: 0.0449 - val_loss: 0.0030 - val_mae: 0.0390
Epoch 150/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0039 - mae: 0.0440 - val_loss: 0.0029 - val_mae: 0.0377
Epoch 151/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0039 - mae: 0.0438 - val_loss: 0.0029 - val_mae: 0.0379
Epoch 152/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0039 - mae: 0.0447 - val_loss: 0.0031 - val_mae: 0.0398
Epoch 153/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0039 - mae: 0.0442 - val_loss: 0.0029 - val_mae: 0.0372
Epoch 154/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0039 - mae: 0.0438 - val_loss: 0.0030 - val_mae: 0.0390
Epoch 155/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0039 - mae: 0.0444 - val_loss: 0.0030 - val_mae: 0.0387
Epoch 156/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0039 - mae: 0.0445 - val_loss: 0.0030 - val_mae: 0.0387
Epoch 157/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0040 - mae: 0.0449 - val_loss: 0.0030 - val_mae: 0.0383
Epoch 158/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0040 - mae: 0.0439 - val_loss: 0.0029 - val_mae: 0.0370
Epoch 159/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0039 - mae: 0.0442 - val_loss: 0.0031 - val_mae: 0.0400
Epoch 160/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0039 - mae: 0.0444 - val_loss: 0.0030 - val_mae: 0.0388
Epoch 161/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0039 - mae: 0.0440 - val_loss: 0.0030 - val_mae: 0.0387
Epoch 162/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0039 - mae: 0.0442 - val_loss: 0.0030 - val_mae: 0.0392
Epoch 163/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0039 - mae: 0.0441 - val_loss: 0.0030 - val_mae: 0.0386
Epoch 164/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0039 - mae: 0.0443 - val_loss: 0.0031 - val_mae: 0.0397
Epoch 165/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0039 - mae: 0.0444 - val_loss: 0.0029 - val_mae: 0.0374
Epoch 166/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0039 - mae: 0.0436 - val_loss: 0.0030 - val_mae: 0.0383
Epoch 167/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0039 - mae: 0.0446 - val_loss: 0.0031 - val_mae: 0.0398
Epoch 168/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0039 - mae: 0.0451 - val_loss: 0.0030 - val_mae: 0.0384
Epoch 169/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0040 - mae: 0.0436 - val_loss: 0.0029 - val_mae: 0.0366
Epoch 170/200
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0039 - mae: 0.0439 - val_loss: 0.0032 - val_mae: 0.0418
Epoch 171/200

In [43]:
y_pred=model.predict(X_test)

3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step

In [47]:
from sklearn.metrics import mean_absolute_error

mae = mean_absolute_error(y_test, y_pred)
print(mae)

94.19357835769654

In [48]:
loss, mae = model.evaluate(X_test, y_test)

print("Test MSE:", loss)
print("Test MAE:", mae)

3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 8885.5498 - mae: 94.1936
Test MSE: 8885.5498046875
Test MAE: 94.1935806274414