<a href="https://colab.research.google.com/github/YashRaj363/ANN_Projects/blob/main/Normalizing_ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [12]:
df=pd.read_csv('Social_Network_Ads.csv')

In [13]:
df.head()

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [14]:
df=df.drop(columns=['User ID'])

In [15]:
df.head()

   Gender  Age  EstimatedSalary  Purchased
0    Male   19            19000          0
1    Male   35            20000          0
2  Female   26            43000          0
3  Female   27            57000          0
4    Male   19            76000          0

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Gender           400 non-null    object
 1   Age              400 non-null    int64
 2   EstimatedSalary  400 non-null    int64
 3   Purchased        400 non-null    int64
dtypes: int64(3), object(1)
memory usage: 12.6+ KB

In [17]:
df.head()

   Gender  Age  EstimatedSalary  Purchased
0    Male   19            19000          0
1    Male   35            20000          0
2  Female   26            43000          0
3  Female   27            57000          0
4    Male   19            76000          0

In [18]:
df.isnull().sum()

Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [19]:
df.duplicated().sum()

np.int64(20)

In [20]:
df[df.duplicated()]

     Gender  Age  EstimatedSalary  Purchased
74     Male   32            18000          0
94   Female   29            83000          0
186  Female   20            82000          0
192    Male   29            43000          0
231    Male   39            42000          0
236    Male   40            57000          0
256  Female   41            72000          0
257    Male   40            57000          0
312  Female   38            50000          0
322    Male   41            52000          0
332    Male   42            65000          0
341    Male   35            75000          0
349    Male   38            61000          0
357  Female   41            72000          0
359    Male   42            54000          0
368    Male   38            71000          0
374  Female   37            80000          0
383    Male   49            28000          1
390    Male   48            33000          1
393    Male   60            42000          1

In [21]:
df.shape

(400, 4)

In [24]:
df = df.drop_duplicates()

In [25]:
df.shape

(380, 4)

In [29]:
df=pd.get_dummies(df,columns=['Gender'],dtype=int)

In [30]:
df.head()

   Age  EstimatedSalary  Purchased  Gender_Female  Gender_Male
0   19            19000          0              0            1
1   35            20000          0              0            1
2   26            43000          0              1            0
3   27            57000          0              1            0
4   19            76000          0              0            1

In [32]:
X=df.drop(columns=['Purchased'])
y=df['Purchased']

In [33]:
X.head()

   Age  EstimatedSalary  Gender_Female  Gender_Male
0   19            19000              0            1
1   35            20000              0            1
2   26            43000              1            0
3   27            57000              1            0
4   19            76000              0            1

In [50]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=43)

In [51]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [36]:
X_train

array([[ 2.00211227,  0.16418382,  0.94244297, -0.94244297],
       [ 1.15872825,  0.51321795,  0.94244297, -0.94244297],
       [-0.0594931 ,  0.04783911, -1.06107216,  1.06107216],
       ...,
       [-0.24691177,  0.04783911,  0.94244297, -0.94244297],
       [ 0.03421624, -0.56297062, -1.06107216,  1.06107216],
       [-0.15320243, -0.47571209,  0.94244297, -0.94244297]])

In [38]:
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping

In [39]:
model=Sequential()

In [40]:
model.add(Dense(128,activation='relu',input_dim=4))
model.add(Dense(1,activation='sigmoid'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [41]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 128)            │           640 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │           129 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 769 (3.00 KB)

 Trainable params: 769 (3.00 KB)

 Non-trainable params: 0 (0.00 B)

In [45]:
model.compile(loss='binary_crossentropy',optimizer='Adam',metrics=['accuracy'])

In [43]:
Call_backs=EarlyStopping(
          monitor='val_loss',
          min_delta=0.00001,
          verbose=1,
          patience=30,
          baseline=None,
          restore_best_weights=False,
          mode='auto'
)

In [52]:
model.fit(X_train,y_train,epochs=1000,callbacks=Call_backs,validation_split=0.2,batch_size=38)

Epoch 1/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.9012 - loss: 0.2423 - val_accuracy: 0.9508 - val_loss: 0.2040
Epoch 2/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9012 - loss: 0.2423 - val_accuracy: 0.9508 - val_loss: 0.2037
Epoch 3/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9012 - loss: 0.2418 - val_accuracy: 0.9508 - val_loss: 0.2034
Epoch 4/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8971 - loss: 0.2418 - val_accuracy: 0.9508 - val_loss: 0.2043
Epoch 5/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9012 - loss: 0.2418 - val_accuracy: 0.9508 - val_loss: 0.2069
Epoch 6/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9012 - loss: 0.2420 - val_accuracy: 0.9508 - val_loss: 0.2064
Epoch 7/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9053 - loss: 0.2413 - val_accuracy: 0.9508 - val_loss: 0.2048
Epoch 8/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9012 - loss: 0.2420 - val_accuracy: 0.9508 - val_loss: 0.2033
Epoch 9/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9012 - loss: 0.2411 - val_accuracy: 0.9508 - val_loss: 0.2038
Epoch 10/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8971 - loss: 0.2412 - val_accuracy: 0.9508 - val_loss: 0.2039
Epoch 11/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8971 - loss: 0.2412 - val_accuracy: 0.9508 - val_loss: 0.2054
Epoch 12/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8971 - loss: 0.2407 - val_accuracy: 0.9508 - val_loss: 0.2058
Epoch 13/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8971 - loss: 0.2404 - val_accuracy: 0.9508 - val_loss: 0.2057
Epoch 14/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8971 - loss: 0.2410 - val_accuracy: 0.9508 - val_loss: 0.2070
Epoch 15/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8971 - loss: 0.2401 - val_accuracy: 0.9508 - val_loss: 0.2068
Epoch 16/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8971 - loss: 0.2398 - val_accuracy: 0.9508 - val_loss: 0.2063
Epoch 17/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9012 - loss: 0.2396 - val_accuracy: 0.9508 - val_loss: 0.2058
Epoch 18/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9012 - loss: 0.2401 - val_accuracy: 0.9508 - val_loss: 0.2058
Epoch 19/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9012 - loss: 0.2400 - val_accuracy: 0.9508 - val_loss: 0.2058
Epoch 20/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9012 - loss: 0.2398 - val_accuracy: 0.9508 - val_loss: 0.2059
Epoch 21/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9012 - loss: 0.2397 - val_accuracy: 0.9508 - val_loss: 0.2063
Epoch 22/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9012 - loss: 0.2392 - val_accuracy: 0.9508 - val_loss: 0.2063
Epoch 23/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9012 - loss: 0.2392 - val_accuracy: 0.9508 - val_loss: 0.2068
Epoch 24/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9012 - loss: 0.2395 - val_accuracy: 0.9508 - val_loss: 0.2081
Epoch 25/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9012 - loss: 0.2390 - val_accuracy: 0.9508 - val_loss: 0.2089
Epoch 26/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9053 - loss: 0.2390 - val_accuracy: 0.9508 - val_loss: 0.2086
Epoch 27/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9012 - loss: 0.2386 - val_accuracy: 0.9508 - val_loss: 0.2097
Epoch 28/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9053 - loss: 0.2385 - val_accuracy: 0.9508 - val_loss: 0.2090
Epoch 29/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9053 - loss: 0.2382 - val_accuracy: 0.9508 - val_loss: 0.2086
Epoch 30/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9053 - loss: 0.2379 - val_accuracy: 0.9508 - val_loss: 0.2073
Epoch 30: early stopping

In [53]:
y_pred=model.predict(X_test)

3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step

In [55]:
from sklearn.metrics import accuracy_score
y_pred_binary = (y_pred > 0.5).astype(int)
accuracy_score(y_test, y_pred_binary)

0.8947368421052632